- name: Configuring backend server.
  hosts: backend
  become: yes
  tasks:
  - name: disabling nodejs old version
    ansible.builtin.command: dnf module disable nodejs -y
  - name: Enabling nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: Installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: create an User
    ansible.builtin.user:
      name: expense
  - name: create a directory
    ansible.builtin.file:
      path: /app 
      state: directory
  - name: download the backend code
    ansible.builtin.get_url:
      url:  https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip
  - name: unzip the file
    ansible.builtin.unarchive:
      src: //tmp/backend.zip
      dest: /app
      remote_src: yes
  - name: Install npm Packages
    community.general.npm:
      path: /app
  - name: Copy the service file
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system/backend.service
  - name: deamon reload and restart the service
    ansible.builtin.systemd:
      enabled: true
      state: restarted
      daemon_reload: true
      name: backend
